[features]
seeds = false
skip-lint = false
[programs.devnet]
unidouble = "J47c2XTaNBzW9d6KvUZth71FzsT9KcKa8bmsZXZVnxyD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mcesbron/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
