[features]
seeds = false
skip-lint = false
[programs.devnet]
unidouble = "C4TX181DDiFWoshCY3S8yMu6agRnz3cov2tQ87XsdimJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mcesbron/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
